name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4,8.0,8.1,8.2,8.3,8.4]
        dependency-version: [prefer-stable, prefer-lowest]
        composer: [v2]

    name: PHP ${{ matrix.php }}  - Composer ${{ matrix.composer }} (${{ matrix.dependency-version }})

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ matrix.composer }}-${{ matrix.dependency-version }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip
        tools: composer:${{ matrix.composer }}
        coverage: pcov

    - name: Install Composer dependencies
      run: |
        composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

    - name: PHPUnit Testing
      run: vendor/bin/phpunit